team: pcm-bookplanning
pipeline: bookplanningexport-mx
slack_channel: "#mbs-deploys"

triggers:
- type: git
  manual_trigger: false
  branch: test 
  shallow: true

feature_toggles:
- update-pipeline

tasks:
- type: run
  name: build
  script: ./build.sh
  docker:
    image: eu.gcr.io/halfpipe-io/pcm-mendix
  save_artifacts:
    - checkout/src
  vars:
    SVN_USERNAME: ((mendix.SVN_USERNAME))
    SVN_PASSWORD: ((mendix.SVN_PASSWORD))
    SVN_PROJECT_ID: b852dae5-6dc5-4b95-a28d-8a994073f3e7 
    
- type: docker-push
  name: create-app-docker-and-push
  image: eu.gcr.io/halfpipe-io/bookplanningexport-mx-katee
  build_history: 5
  restore_artifacts: true
  vars:
    BUILD_PATH: checkout/src
    CF_BUILDPACK: v4.28.4

- type: run
  name: deploy-application-to-katee
  script: \/exe vela up -f ./app/bookplanningexport-mx-katee-test.yml
  docker:
    image: eu.gcr.io/halfpipe-io/ee-katee-vela-cli
  notify_on_success: true
  vars:
    KATEE_TEAM: pcm-bookplan-ex
    KATEE_APPFILE: ./app/bookplanningexport-mx-katee-test.yml
    KATEE_GKE_PROJECT: prod
    KATEE_GKE_CREDENTIALS: ((katee-pcm-bookplan-ex-service-account-prod.key))
    ADMIN_PASSWORD: ((bookplanningexport-mx-test.ADMIN_PASSWORD))
    MXRUNTIME_DatabasePassword: ((bookplanningexport-mx-test.MXRUNTIME_DatabasePassword))
    LICENSE_ID: ((bookplanningexport-mx-test.LICENSE_ID))
    LICENSE_KEY: ((bookplanningexport-mx-test.LICENSE_KEY))
    S3_SECRET_ACCESS_KEY: ((mendix.S3_SECRET_ACCESS_KEY))
    S3_ACCESS_KEY_ID: ((mendix.S3_ACCESS_KEY_ID))
    MX_BpeMain_BookPlanningJdbcPassword: ((bookplanningexport-mx-test.MX_BpeMain_BookPlanningJdbcPassword))
    MX_Cover_DDSWebserviceURL: ((bookplanningexport-mx-test.MX_Cover_DDSWebserviceURL))
    MX_GenericXml_GoogleCredentialsJson: ((bookplanningexport-mx-test.MX_GenericXml_GoogleCredentialsJson))
