team: pcm-bookplanning
pipeline: bookplanningexport-mx
slack_channel: "#book-planning"

triggers:
- type: timer
  cron: "0 */4 * * 1-5"
- type: git
  manual_trigger: true
  branch: test 
  shallow: true

feature_toggles:
- update-pipeline

tasks:
- type: run
  name: build
  script: ./build.sh
  docker:
    image: eu.gcr.io/halfpipe-io/pcm-mendix
  save_artifacts:
    - checkout/src
  vars:
    SVN_USERNAME: ((mendix.SVN_USERNAME))
    SVN_PASSWORD: ((mendix.SVN_PASSWORD))
    SVN_PROJECT_ID: 
    
- type: docker-push
  name: create-app-docker-and-push
  image: eu.gcr.io/halfpipe-io/journalproduction-mx-katee
  build_history: 5
  restore_artifacts: true
  vars:
    BUILD_PATH: checkout/src
    CF_BUILDPACK: v4.28.4

- type: run
  name: deploy-application-to-katee
  script: \/exe vela up -f ./app/bookplanningexport-mx-katee-test.yml
  docker:
    image: eu.gcr.io/halfpipe-io/ee-katee-vela-cli
  notify_on_success: true
  vars:
    KATEE_TEAM: pcm-bookplanning
    KATEE_APPFILE: ./app/bookplanningexport-mx-katee-test.yml
    KATEE_GKE_PROJECT: prod
    KATEE_GKE_CREDENTIALS: ((katee-journalproduction-service-account-prod.key))
    ADMIN_PASSWORD: ((bookplanning-mx-test.ADMIN_PASSWORD))
    MXRUNTIME_DatabasePassword: ((bookplanning-mx-test.MXRUNTIME_DatabasePassword))
    LICENSE_ID: ((bookplanning-mx-test.LICENSE_ID))
    LICENSE_KEY: ((bookplanning-mx-test.LICENSE_KEY))
    S3_SECRET_ACCESS_KEY: ((mendix.S3_SECRET_ACCESS_KEY))
    S3_ACCESS_KEY_ID: ((mendix.S3_ACCESS_KEY_ID))
