apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: bookplanningexport-mx-katee-test
spec:
  components: 
  - type: snstateful
    name: bookplanningexport-mx-katee-test-app
    properties:
      image: eu.gcr.io/halfpipe-io/bookplanningexport-mx-katee:${BUILD_VERSION}
      ports: 
        - name: web
          containerPort: 8080
          servicePort: 8080
          protocol: http
      replicas: 1
      imagePullPolicy: Always
      gpuSupport: false
      resources: 
        cpu: 4
        memory: 8Gi

      env:
        - name: JAVA_OPTS
          value: '["-Xrunjdwp:transport=dt_socket,address=0.0.0.0:8787,server=y,suspend=n", "-Djava.rmi.server.hostname=127.0.0.1", "-Dcom.sun.management.jmxremote.authenticate=false", "-Dcom.sun.management.jmxremote.ssl=false", "-Dcom.sun.management.jmxremote.port=8686", "-Dcom.sun.management.jmxremote.rmi.port=8686"]'

        ### Mendix Basics ###
        - name: LICENSE_ID
          value: '${LICENSE_ID}'
        - name: LICENSE_KEY
          value: '${LICENSE_KEY}'

        - name: MXRUNTIME_ApplicationRootUrl
          value: "https://bookplanningexport-mx-katee-test.apps.private.k8s.springernature.io"
        - name: ADMIN_PASSWORD
          value: '${ADMIN_PASSWORD}'
        - name: MXRUNTIME_DatabaseHost
          value: "gcp-pcm-bpea-test-pgsql-01.cloudsql.de.gcp.springernature.cloud"
        - name: MXRUNTIME_DatabaseName
          value: "bpe-app-test"
        - name: MXRUNTIME_DatabaseType
          value: "PostgreSQL"
        - name: MXRUNTIME_DatabaseUserName
          value: "appuser_test"
        - name: MXRUNTIME_DatabasePassword
          value: '${MXRUNTIME_DatabasePassword}'

        - name: S3_BUCKET_NAME
          value: "sn-mx-bookplanning-exports-test"
        - name: S3_ENDPOINT
          value: "s3-eu-central-1.amazonaws.com"
        - name: S3_SECRET_ACCESS_KEY
          value: '${S3_SECRET_ACCESS_KEY}'
        - name: S3_ACCESS_KEY_ID
          value: '${S3_ACCESS_KEY_ID}'

        - name: MX_DirectBinaryUploader_AWS_BUCKET_NAME
          value: 'sn-mx-bookplanning-exports-test'
        - name: MX_DirectBinaryUploader_AWS_EXPIRES_PERIOD
          value: "604800"
        - name: MX_DirectBinaryUploader_AWS_SECRET_ACCESS_KEY
          value: '${S3_SECRET_ACCESS_KEY}'
        - name: MX_DirectBinaryUploader_AWS_ACCESS_KEY_ID
          value: '${S3_ACCESS_KEY_ID}'

        - name: MX_BpeMain_BookPlanningJdbcUrl
          value: jdbc:postgresql://gcp-bp-test-pgsql-cloudsql-01-rr-01.cloudsql.de.gcp.springernature.cloud/mx_bp_test
        - name: MX_BpeMain_BookPlanningJdbcUser
          value: ro_mx_bp_test
        - name: MX_BpeMain_BookPlanningJdbcPassword
          value: '${MX_BpeMain_BookPlanningJdbcPassword}'
        - name: MX_Cover_DDSWebserviceURL
          value: '${MX_Cover_DDSWebserviceURL}'
        - name: MX_Export_Repository
          value: bookplanning-test
        - name: MX_GenericXml_GoogleCredentialsJson
          value: '${MX_GenericXml_GoogleCredentialsJson}'
        - name: MX_MpsExport_MpsSiNcOutLocation
          value: "https://mobile-base.springernature.com:50601/XISOAPAdapter/MessageServlet?senderParty=&senderService=BC_BFLUX_BOOKS&receiverParty=&receiverService=&interface=SI_NC_OUT&interfaceNamespace=http%3A%2Fspringer.com%2Fxi%2FBFLOW%2FBOOK_TITLES_VERSION_05"
        - name: MX_MpsExport_MpsSiNcBfluxOutLocation
          value: "https://mobile-base.springernature.com:50601/XISOAPAdapter/MessageServlet?senderParty=&senderService=BC_BFLUX_BOOKS&receiverParty=&receiverService=&interface=SI_BFLUX_NC_OUT&interfaceNamespace=http%3A%2Fspringer.com%2Fxi%2FBFLOW%2FBOOK_TITLES_VERSION_05"
        - name: MX_MpsExport_MpsWsPassword
          value: '${MX_MpsExport_MpsWsPassword}'

        - name: MX_Application_ENVIRONMENT_NAME
          value: "Test"

        - name: MX_Application_WorkDirectory
          value: "/persistent-volumes/work"

        - name: VCAP_SERVICES
          value: '{"app-logging":[{"dummy":"dummy"}]}'

        - name: MXRUNTIME_Metrics_Registries
          value: "[{\"type\":\"prometheus\",\"settings\":{\"step\":\"10s\"}}]"
        - name: NGINX_CUSTOM_LOCATIONS
          value: '{"/metrics": {"body": "proxy_pass http://127.0.0.1:8082/prometheus;\nallow all;"}}'

    traits:
    - type:  sningress
      properties:
        privateRoutes:
          - route: bookplanningexport-mx-katee-test.apps.private.k8s.springernature.io
            #cname: bookplanningexport-test.springernature.com
            servicePort: 8080

    - type: snpvc
      properties:
        name: extended-storage
        # Increasing this value has no effect after initial cration of the volume.
        # To increase the size contact PCM Architecture enablement. 
        storageSize: 20Gi
        volumesToMount:
        - name: extended-storage
          mountPath: /persistent-volumes/work
          
  #- type: sngrafana
    #name: sngrafana-app
    #properties:
      #useV2: true
      #route:  bookplanningexport-grafana-test.apps.private.k8s.springernature.io
      #vault:
        #team: pcm-bookplanning
        #adminSecret: grafana-admin-creds
